Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('category-list/', views.category_list, name='category_list'),
    path('category-create/', views.category_create, name='category_create'),
    path('category-update/<str:code>/', views.category_update, name='category_update'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    path('product-list/', views.product_list, name='product_list'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-update/<str:code>/', views.product_update, name='product_update'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    path('product-img-delete/<int:id>/', views.product_img_delete,name='product_img_delete'),
    path('product-video-delete/<int:id>/', views.product_video_delete,name='product_video_delete'),
    path('create-product-enter/', views.create_product_enter,name='create_product_enter'),
    path('list-product-enter/', views.list_product_enter,name='list_product_enter'),
    path('update-product-enter/<str:code>/', views.update_product_enter,name='update_product_enter'),
    path('detail-product-enter/<str:code>/', views.detail_product_enter,name='detail_product_enter'),
    path('product-history/<str:code>/', views.product_history,name='product_history'),

]

main/dashboard/views.py
from django.shortcuts import render, redirect
from main.funcs import staff_required
from main import models
from itertools import chain

@staff_required
def index(request):
    context = {}
    return render(request, 'dashboard/index.html', context)


@staff_required
def category_list(request):
    queryset = models.Category.objects.all()
    context = {
        'queryset':queryset
        }
    return render(request, 'dashboard/category/list.html', context)


@staff_required
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')


@staff_required
def category_update(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.name = request.POST['name']
    queryset.save()
    return redirect('dashboard:category_list')


@staff_required
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------PRODUCT----------------

@staff_required
def product_list(request):
    categories = models.Category.objects.all()
    category_code = request.GET.get('category_code')
    if category_code and category_code != '0':
        print(request.POST)
        print(request.GET)
        if request.GET.get('is_discount'):
            queryset = models.Product.objects.filter(
                category__code=category_code,
                name__icontains=request.GET.get('name'),
                quantity=request.GET.get('quantity'),
                discount_price__isnull = False
                )
        else:
            queryset = models.Product.objects.filter(
                category__code=category_code,
                name__icontains=request.GET.get('name'),
                quantity=request.GET.get('quantity'),
                discount_price__isnull = True
                )
    else:
        queryset = models.Product.objects.all()
    context = {
          'queryset':queryset,
          'categories':categories,
          'category_code':category_code,
    }
    return render(request, 'dashboard/product/list.html', context)


@staff_required
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImg.objects.filter(product=queryset)
    reviews = models.Review.objects.filter(product=queryset)
    ratings = range(5,0,-1)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
          'queryset':queryset,
          'images':images,
          'reviews':reviews,
          'ratings':ratings,
          'videos':videos
    }
    return render(request, 'dashboard/product/detail.html', context)
    

@staff_required
def product_create(request):
    categorys = models.Category.objects.all()
    context = {'categorys':categorys}
    if request.method == 'POST':
        delivery = True if request.POST.get('delivery') else False
        product = models.Product.objects.create(
            category_id = request.POST.get('category_id'),
            name = request.POST.get('name'),
            body = request.POST.get('body'),
            price = request.POST.get('price'),
            banner_img = request.FILES.get('banner_img'),
            quantity = request.POST.get('quantity'),
            delivery = delivery
        )
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', context)


@staff_required
def product_update(request, code):

    images = models.ProductImg.objects.filter(product__code=code)
    videos = models.ProductVideo.objects.filter(product__code=code)
    categories = models.Category.objects.all()
    product = models.Product.objects.get(code=code)

    if request.method == 'POST':
        if request.FILES.get('banner_img'):
            product.banner_img = request.FILES.get('banner_img')
        delivery = True if request.POST.get('delivery') else False
        product.category_id = request.POST.get('category_id')
        product.name = request.POST.get('name')
        product.body = request.POST.get('body')
        product.price = request.POST.get('price')
        product.delivery = delivery
        product.save()
    
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_update',product.code)
    
    context = {
          'images':images,
          'videos':videos,
          'categories':categories,
          'product':product

    }
    return render(request,'dashboard/product/update.html',context=context)


@staff_required
def product_delete(request, code):
    product = models.Product.objects.get(code=code)
    product.delete()
    return redirect('dashboard:product_list')


@staff_required
def product_img_delete(request, id):
    product_img = models.ProductImg.objects.get(id=id)
    product_img.delete()
    return redirect('dashboard:product_update',product_img.product_id)


@staff_required
def product_video_delete(request, id):
    product_video = models.ProductVideo.objects.get(id=id)
    product_video.delete()
    return redirect('dashboard:product_update',product_video.product_id)


@staff_required
def create_product_enter(request):
    products = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST.get('product_code'))
        quantity = request.POST.get('quantity')
        models.EnterProduct.objects.create(
            product = product,
            quantity = quantity
        )
        redirect('dashboard:product_list')

    context = {
        'products':products
    }
    
    return render(request,'dashboard/enter_product/create.html',context)



@staff_required
def update_product_enter(request,code):
    if request.method == 'POST':
        enter_product = models.EnterProduct.objects.get(code=code)
        quantity = request.POST.get('quantity')
        enter_product.quantity = quantity
        enter_product.save()
    return redirect('dashboard:list_product_enter')
    


@staff_required
def list_product_enter(request):
    products = models.Product.objects.all()
    context = {
          'products':products
    }
    return render(request, 'dashboard/enter_product/list.html', context)


@staff_required
def detail_product_enter(request,code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    context = {
          'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/detail.html', context)


@staff_required
def product_history(request,code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    outs = models.CartProduct.objects.filter(product__code=code,cart__status=4)
    data = list(chain(queryset, outs))
    data = sorted(data, key=lambda x: x.date, reverse=True)
    context = {
          'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/history.html', context)

templates/dashboard/enter_product/create.html
{% extends 'dashboard/base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">SHOP</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Maxsulot</a>
                    <span class="breadcrumb-item active">Qo`shish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Maxsulot qo`shish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Mahsulot</label>
                            <div class="col-sm-10">
                                <select name="product_code" class="form-control">
                                    {% for product in products %}
                                    <option value="{{product.code}}">{{product.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Soni</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="inputPassword3" placeholder="..." name="quantity">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Yaratish</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->


{% endblock %}

templates/dashboard/enter_product/detail.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Enter Product</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-around">
            <h4>Enter Productlar ro`yxat</h4>
            <div>
                <form class="input-group input-group-sm mb-3">
                    <select name="category_code" class="form-control">
                        <option value="0">Barchasi</option>
                        {% for category in categories %}
                        <option value="{{category.code}}" {% if category.code == category_code %} selected {% endif %}>{{category}}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-prepend">
                        <button class="input-group-text" id="inputGroup-sizing-sm" type="submit">Filterlash</button>
                    </div>
                </form>
            </div>
            </div>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Product</th>
                                <th scope="col">Kirim</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.product.name}}</td>
                                <td style="color: rgb;">+{{q.quantity}}</td>
                                <td>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-edit"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.product.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.product.name}} miqdorini o`zgartirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:update_product_enter' q.code %}">
                                                        {% csrf_token %}
                                                        <div class="modal-body">
                                                            <input type="number" class="form-control" value="{{q.quantity}}" name="quantity">
                                                        </div>
                                                        <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/enter_product/history.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Enter Product</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-around">
            <h4>Enter Productlar ro`yxat</h4>
            <div>
                <form class="input-group input-group-sm mb-3">
                    <select name="category_code" class="form-control">
                        <option value="0">Barchasi</option>
                        {% for category in categories %}
                        <option value="{{category.code}}" {% if category.code == category_code %} selected {% endif %}>{{category}}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-prepend">
                        <button class="input-group-text" id="inputGroup-sizing-sm" type="submit">Filterlash</button>
                    </div>
                </form>
            </div>
            </div>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Product</th>
                                <th scope="col">Kirim/Chiqim</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.product.name}}</td>
                                {% if q.quantity %}
                                <td style="color: green;">+{{q.quantity}}</td>
                                <td>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-edit"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.product.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.product.name}} miqdorini o`zgartirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:update_product_enter' q.code %}">
                                                        {% csrf_token %}
                                                        <div class="modal-body">
                                                            <input type="number" class="form-control" value="{{q.quantity}}" name="quantity">
                                                        </div>
                                                        <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                {% else %}
                                <td style="color: red;">-{{q.count}}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/enter_product/list.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Product</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Enter Productlar ro`yxati</h4>
            
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Category</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{product.category.name}}</td>
                                <td>{{product.name}}</td>
                                <td>
                                    <a href="{% url 'dashboard:detail_product_enter' product.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-eye"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}