Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/auth/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/',views.log_in,name='login'),
    path('logout/',views.log_out,name='logout'),
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
]

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('category-list/', views.category_list, name='category_list'),
    path('category-create/', views.category_create, name='category_create'),
    path('category-update/<str:code>/', views.category_update, name='category_update'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    path('product-list/', views.product_list, name='product_list'),
    path('product-create/', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-update/<str:code>/', views.product_update, name='product_update'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    path('product-img-delete/<int:id>/', views.product_img_delete,name='product_img_delete'),
    path('product-video-delete/<int:id>/', views.product_video_delete,name='product_video_delete'),
    path('create-product-enter/', views.create_product_enter,name='create_product_enter'),
    path('list-product-enter/', views.list_product_enter,name='list_product_enter'),
    path('update-product-enter/<str:code>/', views.update_product_enter,name='update_product_enter'),
    path('detail-product-enter/<str:code>/', views.detail_product_enter,name='detail_product_enter'),
    path('product-history/<str:code>/', views.product_history,name='product_history'),

]

main/dashboard/views.py
from django.shortcuts import render, redirect
from main.funcs import staff_required
from main import models
from itertools import chain

@staff_required
def index(request):
    context = {}
    return render(request, 'dashboard/index.html', context)


@staff_required
def category_list(request):
    queryset = models.Category.objects.all()
    context = {
        'queryset':queryset
        }
    return render(request, 'dashboard/category/list.html', context)


@staff_required
def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')


@staff_required
def category_update(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.name = request.POST['name']
    queryset.save()
    return redirect('dashboard:category_list')


@staff_required
def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------PRODUCT----------------

@staff_required
def product_list(request):
    categories = models.Category.objects.all()
    category_code = request.GET.get('category_code')
    if category_code and category_code != '0':
        print(request.POST)
        print(request.GET)
        if request.GET.get('is_discount'):
            queryset = models.Product.objects.filter(
                category__code=category_code,
                name__icontains=request.GET.get('name'),
                quantity=request.GET.get('quantity'),
                discount_price__isnull = False
                )
        else:
            queryset = models.Product.objects.filter(
                category__code=category_code,
                name__icontains=request.GET.get('name'),
                quantity=request.GET.get('quantity'),
                discount_price__isnull = True
                )
    else:
        queryset = models.Product.objects.all()
    context = {
          'queryset':queryset,
          'categories':categories,
          'category_code':category_code,
    }
    return render(request, 'dashboard/product/list.html', context)


@staff_required
def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImg.objects.filter(product=queryset)
    reviews = models.Review.objects.filter(product=queryset)
    ratings = range(5,0,-1)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
          'queryset':queryset,
          'images':images,
          'reviews':reviews,
          'ratings':ratings,
          'videos':videos
    }
    return render(request, 'dashboard/product/detail.html', context)
    

@staff_required
def product_create(request):
    categorys = models.Category.objects.all()
    context = {'categorys':categorys}
    if request.method == 'POST':
        delivery = True if request.POST.get('delivery') else False
        product = models.Product.objects.create(
            category_id = request.POST.get('category_id'),
            name = request.POST.get('name'),
            body = request.POST.get('body'),
            price = request.POST.get('price'),
            banner_img = request.FILES.get('banner_img'),
            quantity = request.POST.get('quantity'),
            delivery = delivery
        )
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', context)


@staff_required
def product_update(request, code):

    images = models.ProductImg.objects.filter(product__code=code)
    videos = models.ProductVideo.objects.filter(product__code=code)
    categories = models.Category.objects.all()
    product = models.Product.objects.get(code=code)

    if request.method == 'POST':
        if request.FILES.get('banner_img'):
            product.banner_img = request.FILES.get('banner_img')
        delivery = True if request.POST.get('delivery') else False
        product.category_id = request.POST.get('category_id')
        product.name = request.POST.get('name')
        product.body = request.POST.get('body')
        product.price = request.POST.get('price')
        product.delivery = delivery
        product.save()
    
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_update',product.code)
    
    context = {
          'images':images,
          'videos':videos,
          'categories':categories,
          'product':product

    }
    return render(request,'dashboard/product/update.html',context=context)


@staff_required
def product_delete(request, code):
    product = models.Product.objects.get(code=code)
    product.delete()
    return redirect('dashboard:product_list')


@staff_required
def product_img_delete(request, id):
    product_img = models.ProductImg.objects.get(id=id)
    product_img.delete()
    return redirect('dashboard:product_update',product_img.product_id)


@staff_required
def product_video_delete(request, id):
    product_video = models.ProductVideo.objects.get(id=id)
    product_video.delete()
    return redirect('dashboard:product_update',product_video.product_id)


@staff_required
def create_product_enter(request):
    products = models.Product.objects.all()
    if request.method == 'POST':
        product = models.Product.objects.get(code=request.POST.get('product_code'))
        quantity = request.POST.get('quantity')
        models.EnterProduct.objects.create(
            product = product,
            quantity = quantity
        )
        redirect('dashboard:product_list')

    context = {
        'products':products
    }
    
    return render(request,'dashboard/enter_product/create.html',context)



@staff_required
def update_product_enter(request,code):
    if request.method == 'POST':
        enter_product = models.EnterProduct.objects.get(code=code)
        quantity = request.POST.get('quantity')
        enter_product.quantity = quantity
        enter_product.save()
    return redirect('dashboard:list_product_enter')
    


@staff_required
def list_product_enter(request):
    products = models.Product.objects.all()
    context = {
          'products':products
    }
    return render(request, 'dashboard/enter_product/list.html', context)


@staff_required
def detail_product_enter(request,code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    context = {
          'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/detail.html', context)


@staff_required
def product_history(request,code):
    queryset = models.EnterProduct.objects.filter(product__code=code)
    outs = models.CartProduct.objects.filter(product__code=code,cart__status=4)
    data = list(chain(queryset, outs))
    data = sorted(data, key=lambda x: x.date, reverse=True)
    context = {
          'queryset':queryset
    }
    return render(request, 'dashboard/enter_product/history.html', context)

templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin Dashboard Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'dashboard/images/logo/favicon.png' %}">

    <!-- page css -->
    <link href="{% static 'dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">

    <!-- Core css -->
    <link href="{% static 'dashboard/css/app.min.css' %}" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="{% url 'dashboard:index' %}">
                        <img src="{% static 'dashboard/images/logo/logo.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'dashboard/images/logo/logo-fold.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="{% url 'dashboard:index' %}">
                        <img src="{% static 'dashboard/images/logo/logo-white.png' %}" alt="Logo">
                        <img class="logo-fold" src="{% static 'dashboard/images/logo/logo-fold-white.png' %}" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="{{user.avatar.url}}"  alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="{{user.avatar.url}}" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold">{{user.username}}</p>
                                        </div>
                                    </div>
                                </div>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                            <span class="m-l-10">Edit Profile</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                            <span class="m-l-10">Account Setting</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                            <span class="m-l-10">Projects</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="{% url 'auth:logout' %}" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Logout</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>    
            <!-- Header END -->


            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="nav-item dropdown open">
                            <a class="dropdown-toggle" href="javascript:void(0);">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Shop menu</span>
                                <span class="arrow">
                                    <i class="arrow-icon"></i>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="anticon anticon-ordered-list"></i>
                                            </span>
                                            <span class="title">Category</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:category_create' %}">
                                                    <i class="anticon anticon-plus-circle"></i>
                                                    Create
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:category_list' %}">
                                                    <span class="icon-holder">
                                                        <i class="fas fa-align-justify"></i>
                                                        List
                                                    </span>
                                                      
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                                
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="anticon anticon-heat-map"></i>
                                            </span>
                                            <span class="title">Product</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:product_create' %}">
                                                    <i class="anticon anticon-plus-circle"></i>
                                                    Create
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:product_list' %}">
                                                    <i class="fas fa-align-justify"></i>
                                                    List
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                                <li>
                                    <li class="nav-item dropdown open">
                                        <a class="dropdown-toggle" href="javascript:void(0);">
                                            <span class="icon-holder">
                                                <i class="anticon anticon-heat-map"></i>
                                            </span>
                                            <span class="title">Enter Product</span>
                                            <span class="arrow">
                                                <i class="arrow-icon"></i>
                                            </span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'dashboard:create_product_enter' %}">
                                                    <i class="anticon anticon-plus-circle"></i>
                                                    Create
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'dashboard:list_product_enter' %}">
                                                    <i class="fas fa-align-justify"></i>
                                                    List
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </li>
                                <!-- <li class="active">
                                    <a href="index-projects.html">Projects</a>
                                </li> -->
                            </ul>
                        </li>
                       
                        
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="page-container">
                
                {% block content %}
                {% endblock %}
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                            <a href="" class="text-gray">Privacy &amp; Policy</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="{% static 'dashboard/js/vendors.min.js' %}"></script>

    <!-- page js -->
    <script src="{% static 'dashboard/vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'dashboard/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'dashboard/js/pages/dashboard-project.js' %}"></script>
    

    <!-- Core JS -->
    <script src="{% static 'dashboard/js/app.min.js' %}"></script>

</body>

</html>

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% load static %}
{% block content %}
<!-- Content Wrapper START -->
         <div class="main-content">
            <div class="page-header no-gutters">
                <div class="d-md-flex align-items-md-center justify-content-between">
                    <div class="media m-v-10 align-items-center">
                        <div class="avatar avatar-image avatar-lg">
                            <img src="{% static 'dashboard/images/avatars/thumb-3.jpg' %}" alt="">
                        </div>
                        <div class="media-body m-l-15">
                            <h4 class="m-b-0">Welcome back, Nichols!</h4>
                            <span class="text-gray">Project Manager</span>
                        </div>
                    </div>
                    <div class="d-md-flex align-items-center d-none">
                        <div class="media align-items-center m-r-40 m-v-5">
                            <div class="font-size-27">
                                <i class="text-primary anticon anticon-profile"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">78</h2>
                                <span class="text-gray">Tasks</span>
                            </div>
                        </div>
                        <div class="media align-items-center m-r-40 m-v-5">
                            <div class="font-size-27">
                                <i class="text-success  anticon anticon-appstore"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">21</h2>
                                <span class="text-gray">Projects</span>
                            </div>
                        </div>
                        <div class="media align-items-center m-v-5">
                            <div class="font-size-27">
                                <i class="text-danger anticon anticon-team"></i>
                            </div>
                            <div class="d-flex align-items-center m-l-10">
                                <h2 class="m-b-0 m-r-5">39</h2>
                                <span class="text-gray">Members</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Wrapper END -->
{% endblock %}